services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: deps
    container_name: monorepo-backend-dev
    working_dir: /usr/src/app
    command: pnpm --filter backend start:dev
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/usr/src/app/apps/backend
      - /usr/src/app/node_modules
      - /usr/src/app/apps/backend/node_modules
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: deps
    container_name: monorepo-frontend-dev
    working_dir: /usr/src/app
    command: pnpm --filter frontend dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/usr/src/app/apps/frontend
      - /usr/src/app/node_modules
      - /usr/src/app/apps/frontend/node_modules
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
      - backend
